import assert from 'node:assert/strict';
import { useResearchStore } from '../src/store/useResearchStore';
import { compareResearchFindings, getResearchIntegrationRecords, normalizeDoi, parseResearchSnapshot, researchReviewIssues, safeResearchUrl, validateResearchFinding, validateResearchSource } from '../src/utils/researchRegistry';
import type { ResearchFinding, ResearchSource } from '../src/types/research';

// Deliberately synthetic contract fixtures. These are never registered as application evidence.
const source: ResearchSource = { id: 'source-fixture', briefId: 'brief-fixture', title: 'Synthetic contract fixture — not scientific evidence', authors: 'Test fixture', year: 2020, doi: '10.1234/test-fixture', url: '', sourceType: 'primary-paper', confidence: 'low', notes: 'Test only', createdAt: '2026-09-13T00:00:00Z' };
const finding: ResearchFinding = { id: 'finding-fixture', briefId: source.briefId, sourceId: source.id, materialId: 'material-fixture', materialName: 'Synthetic fixture', property: 'Test width', value: 10, unit: 'µm', uncertainty: 2, uncertaintyDescription: 'Test interval only', conditions: { composition: 'Fixture', process: 'Fixture process', machine: 'Fixture machine', processParameters: 'Fixture parameters', powderCondition: 'Not applicable', heatTreatment: 'Not applicable', measurementMethod: 'Fixture method' }, locator: 'Test table', evidenceType: 'measured', confidence: 'low', limitations: 'Synthetic fixture, no physical interpretation', validationReference: '', targetModule: 'validation-dataset', reviewStatus: 'draft', reviewNote: 'Fixture reviewed only to exercise contract logic', conflictsWith: [], createdAt: '2026-09-13T00:00:00Z' };
assert.equal(normalizeDoi('https://doi.org/10.1234/TEST-fixture'), '10.1234/test-fixture');
assert.equal(safeResearchUrl('javascript:alert(1)'), '');
assert.equal(safeResearchUrl('file:///private'), '');
assert.deepEqual(validateResearchSource(source), []);
for (const patch of [{ doi: 'missing-doi' }, { url: 'data:text/html,test' }, { year: Infinity }, { confidence: 'fabricated' }]) assert.ok(validateResearchSource({ ...source, ...patch } as ResearchSource).length);
assert.deepEqual(validateResearchFinding(finding, source), []);
for (const patch of [{ value: NaN }, { value: Infinity }, { unit: '' }, { uncertainty: -1 }, { rangeLow: 12, rangeHigh: 20 }, { rangeLow: 20, rangeHigh: 12 }, { rangeLow: 0 }, { confidence: 'fabricated' }]) assert.ok(validateResearchFinding({ ...finding, ...patch } as ResearchFinding, source).length);
assert.ok(researchReviewIssues({ ...finding, evidenceType: 'validated-simulation' }, source).some(issue => issue.includes('experimental validation')));
assert.ok(researchReviewIssues(finding, { ...source, sourceType: 'review' }).some(issue => issue.includes('original primary source')));
assert.match(compareResearchFindings(finding, { ...finding, unit: 'mm' }), /Different units/);
assert.match(compareResearchFindings(finding, { ...finding, conditions: { ...finding.conditions, heatTreatment: 'Different' } }), /Conditions differ/);
assert.match(compareResearchFindings(finding, { ...finding, value: 30 }), /do not overlap/);
assert.match(compareResearchFindings(finding, { ...finding, value: 11 }), /does not establish validation/);
assert.match(compareResearchFindings(finding, { ...finding, uncertainty: undefined }), /missing/);

const state = () => useResearchStore.getState();
const briefResult = state().addBrief({ question: 'Synthetic fixture workflow', alloy: 'Fixture', process: 'Fixture', method: 'Fixture', dataType: 'Fixture' });
assert.deepEqual(briefResult.errors, []);
const sourceResult = state().addSource({ ...source, briefId: briefResult.id! });
assert.deepEqual(sourceResult.errors, []);
assert.ok(state().addSource({ ...source, briefId: briefResult.id! }).errors.length, 'Duplicate DOI in one brief must be blocked');
const f1 = state().addFinding({ ...finding, briefId: briefResult.id!, sourceId: sourceResult.id! });
assert.deepEqual(f1.errors, []);
assert.ok(state().integrateFinding(f1.id!, 'validation-dataset').errors.length, 'Draft extraction cannot integrate');
assert.deepEqual(state().reviewFinding(f1.id!, finding.reviewNote).errors, []);
assert.deepEqual(state().integrateFinding(f1.id!, 'validation-dataset').errors, []);
assert.deepEqual(state().integrateFinding(f1.id!, 'validation-dataset').errors, []);
assert.equal(state().integrations.length, 1, 'Integration is idempotent');
assert.equal(getResearchIntegrationRecords(state(), 'validation-dataset', finding.materialId).length, 1);
assert.equal(getResearchIntegrationRecords(state(), 'validation-dataset', 'other-material').length, 0);
const exported = JSON.parse(JSON.stringify(state().exportSnapshot()));
assert.deepEqual(parseResearchSnapshot(exported), exported);
assert.deepEqual(state().importSnapshot(exported).errors, [], 'Reimport preserves identical records');
assert.equal(state().findings.length, 1);
const badOrphan = structuredClone(exported); badOrphan.findings[0].sourceId = 'missing';
assert.throws(() => parseResearchSnapshot(badOrphan));
const badValidation = structuredClone(exported); badValidation.findings[0].evidenceType = 'validated-simulation';
assert.throws(() => parseResearchSnapshot(badValidation));
const badUrl = structuredClone(exported); badUrl.sources[0].url = 'javascript:alert(1)';
assert.throws(() => parseResearchSnapshot(badUrl));
const badDuplicate = structuredClone(exported); badDuplicate.sources.push(badDuplicate.sources[0]);
assert.throws(() => parseResearchSnapshot(badDuplicate));
const changedRecord = structuredClone(exported); changedRecord.findings[0].value = 100;
assert.ok(state().importSnapshot(changedRecord).errors.length, 'Conflicting imports must preserve current work');
assert.equal(state().findings[0].value, 10);
const second = state().addFinding({ ...finding, briefId: briefResult.id!, sourceId: sourceResult.id!, value: 30 });
assert.deepEqual(state().setConflict(f1.id!, second.id!, true).errors, []);
const asymmetricConflict = JSON.parse(JSON.stringify(state().exportSnapshot()));
asymmetricConflict.findings.find((f: ResearchFinding) => f.id === second.id).conflictsWith = [];
assert.throws(() => parseResearchSnapshot(asymmetricConflict), /reciprocal/, 'One-sided imported conflicts cannot bypass integration guards');
assert.equal(state().integrations.length, 0, 'Flagging conflicts withdraws both module links');
assert.ok(state().findings.find(f => f.id === second.id)?.conflictsWith.includes(f1.id!));
assert.ok(state().integrateFinding(f1.id!, 'validation-dataset').errors.length);
assert.deepEqual(state().setConflict(f1.id!, second.id!, false).errors, []);
assert.deepEqual(state().integrateFinding(f1.id!, 'lpbf-solver').errors, []);
assert.deepEqual(state().addFeedback({ findingId: f1.id!, outcome: 'contradicts', note: 'Fixture contradicts fixture', experimentOrJobReference: 'test-job' }).errors, []);
assert.equal(state().findings.find(f => f.id === f1.id)?.reviewStatus, 'draft');
assert.equal(state().integrations.length, 0, 'Contradictory feedback requires a new review');
assert.deepEqual(state().reviewFinding(f1.id!, 'Re-reviewed fixture and contradictory observation').errors, []);
assert.deepEqual(state().integrateFinding(f1.id!, 'materials-db').errors, []);
assert.deepEqual(state().updateSource(sourceResult.id!, { ...source, briefId: briefResult.id!, notes: 'Corrected source metadata' }).errors, []);
assert.equal(state().integrations.length, 0, 'Source corrections invalidate earlier links');
assert.ok(state().findings.every(f => f.reviewStatus === 'draft'));
assert.deepEqual(state().reviseFinding(f1.id!, { ...finding, briefId: briefResult.id!, sourceId: sourceResult.id!, evidenceType: 'screening-only' }).errors, []);
assert.deepEqual(state().reviewFinding(f1.id!, 'Screening fixture review').errors, []);
assert.ok(state().integrateFinding(f1.id!, 'validation-dataset').errors.length, 'Screening output cannot be ground truth');
assert.deepEqual(state().integrateFinding(f1.id!, 'lpbf-solver').errors, []);
assert.deepEqual(parseResearchSnapshot(JSON.parse(JSON.stringify(state().exportSnapshot()))), JSON.parse(JSON.stringify(state().exportSnapshot())));
console.log('Research registry: provenance, review, conflict withdrawal, feedback, import integrity, scope and numeric guards passed.');
