import React, { useRef, useState } from 'react';
import { ExternalLink, Search } from 'lucide-react';
import { useResearchStore } from '../../store/useResearchStore';
import { SOURCE_TYPES, type ResearchConfidence, type ResearchSourceType } from '../../types/research';
import { normalizeDoi, researchLabel, sourceLink } from '../../utils/researchRegistry';
import { Badge, Empty, Field, Notice, Select, buttonClass, confidences, panelClass, primaryClass, useDraft } from './ResearchControls';

const sourceDefaults = { title: '', authors: '', year: '', doi: '', url: '', sourceType: 'primary-paper', confidence: 'unresolved', notes: '', editId: '' };
type SearchSource = { title: string; authors: string[]; year: number | null; doi: string; url: string; publicationType: string };

export function ResearchSourcesPanel() {
  const state = useResearchStore(), brief = state.briefs.find(item => item.id === state.activeBriefId)!;
  const { draft, patch, replace } = useDraft(`source:${brief.id}`, sourceDefaults);
  const searchDraft = useDraft(`search:${brief.id}`, { query: [brief.alloy, brief.process, brief.method, brief.dataType, brief.question].filter(Boolean).join(' '), filter: '' });
  const [results, setResults] = useState<SearchSource[]>([]), [loading, setLoading] = useState(false), [searched, setSearched] = useState(false), [searchErrors, setSearchErrors] = useState<string[]>([]), [errors, setErrors] = useState<string[]>([]);
  const request = useRef<AbortController | null>(null);
  React.useEffect(() => () => { request.current?.abort(); request.current = null; }, []);
  const sources = state.sources.filter(source => source.briefId === brief.id && (!searchDraft.draft.filter || source.sourceType === searchDraft.draft.filter));
  async function search() {
    request.current?.abort(); const controller = new AbortController(); request.current = controller;
    setLoading(true); setSearchErrors([]); setSearched(true); setResults([]); const timeout = setTimeout(() => controller.abort(), 20000);
    try {
      const response = await fetch(`/api/research/search?q=${encodeURIComponent(searchDraft.draft.query)}`, { signal: controller.signal });
      const data = await response.json(); if (!response.ok) throw new Error(data.error || `Literature search unavailable (${response.status}).`);
      if (!Array.isArray(data.items)) throw new Error('Search returned an unsupported response. Use DOI or direct-link intake below.');
      if (request.current === controller) setResults(data.items.filter((source: SearchSource) => typeof source.title === 'string' && typeof source.doi === 'string' && typeof source.url === 'string' && Array.isArray(source.authors)));
    } catch (error) { if (request.current === controller) setSearchErrors([controller.signal.aborted ? 'Search timed out or was cancelled. Retry, open Crossref, or add a source manually.' : error instanceof Error ? error.message : 'Literature search unavailable.']); }
    finally { clearTimeout(timeout); if (request.current === controller) setLoading(false); }
  }
  return <div className="space-y-5"><section className={panelClass}><h2 className="text-lg font-semibold text-slate-100">Literature search</h2><p className="my-2 text-xs text-slate-400">Crossref provides bibliographic metadata. Read the original source before extracting values. A DOI format check does not verify its contents.</p><form className="flex flex-wrap items-end gap-3" onSubmit={event => { event.preventDefault(); void search(); }}><div className="min-w-60 flex-1"><Field label="Alloy, process, method, data type, or DOI" value={searchDraft.draft.query} onChange={value => searchDraft.patch('query', value)} required /></div><button type="submit" className={primaryClass} disabled={loading}>{loading ? 'Searching…' : <><Search size={14} /> Search literature</>}</button><a className={buttonClass} href={`https://search.crossref.org/?q=${encodeURIComponent(searchDraft.draft.query)}`} target="_blank" rel="noreferrer">Open Crossref <ExternalLink size={13} /></a></form><div className="mt-4"><Notice messages={searchErrors} /></div>{loading && <p role="status" className="mt-3 text-sm text-sky-300">Retrieving source metadata…</p>}{searched && !loading && !results.length && !searchErrors.length && <Empty>No results for this query. Refine the terms or add a source by DOI.</Empty>}{results.length > 0 && <div className="mt-4 divide-y divide-slate-800">{results.map((source, index) => <div key={`${source.doi}-${index}`} className="flex items-center justify-between gap-4 py-3"><div><p className="text-sm text-slate-200">{source.title}</p><p className="mt-1 text-xs text-slate-500">{source.authors.join(', ')} · {source.year ?? 'Year unreported'} · {source.doi || 'No DOI'} · {source.publicationType}</p></div><button className={buttonClass} onClick={() => { replace({ ...sourceDefaults, title: source.title, authors: source.authors.join(', '), doi: source.doi, url: source.url, year: source.year?.toString() ?? '', notes: `Metadata discovered via Crossref (${source.publicationType}). Full text and source type require review.` }); setErrors([]); }}>Use metadata</button></div>)}</div>}</section>
    <div className="grid gap-5 xl:grid-cols-2"><section className={panelClass}><h2 className="mb-4 text-lg font-semibold text-slate-100">{draft.editId ? 'Edit saved source' : 'Register a source'}</h2><form className="space-y-4" onSubmit={event => { event.preventDefault(); const source = { briefId: brief.id, title: draft.title, authors: draft.authors, year: draft.year.trim() ? Number(draft.year) : undefined, doi: draft.doi, url: draft.url, sourceType: draft.sourceType as ResearchSourceType, confidence: draft.confidence as ResearchConfidence, notes: draft.notes }; const result = draft.editId ? state.updateSource(draft.editId, source) : state.addSource(source); setErrors(result.errors); if (!result.errors.length) replace(sourceDefaults); }}>
      <Field label="Source title" value={draft.title} onChange={value => patch('title', value)} required /><div className="grid gap-4 sm:grid-cols-2"><Field label="Authors / issuing organization" value={draft.authors} onChange={value => patch('authors', value)} /><Field label="Publication year" type="number" value={draft.year} onChange={value => patch('year', value)} /><Field label="DOI" value={draft.doi} onChange={value => patch('doi', value)} placeholder="10.… or https://doi.org/…" /><Field label="Direct source link" value={draft.url} onChange={value => patch('url', value)} placeholder="https://…" /><Select label="Source type (verify in original)" value={draft.sourceType} onChange={value => patch('sourceType', value)} options={SOURCE_TYPES} /><Select label="Source confidence (user assessed)" value={draft.confidence} onChange={value => patch('confidence', value)} options={confidences} /></div><Field label="Source assessment / access limitations" value={draft.notes} onChange={value => patch('notes', value)} multiline /><Notice messages={errors} /><div className="flex gap-2"><button className={primaryClass} type="submit">{draft.editId ? 'Save revision (requires new review)' : 'Save source'}</button>{draft.editId && <button type="button" className={buttonClass} onClick={() => replace(sourceDefaults)}>Cancel edit</button>}</div></form></section>
      <section className={panelClass}><div className="mb-4 flex items-end justify-between gap-3"><h2 className="text-lg font-semibold text-slate-100">Saved sources</h2><Select label="Filter type" value={searchDraft.draft.filter} onChange={value => searchDraft.patch('filter', value)} options={[{ value: '', label: 'All source types' }, ...SOURCE_TYPES.map(value => ({ value, label: researchLabel(value) }))]} /></div>{!sources.length ? <Empty>No sources match this brief and filter. Search or register a source to begin.</Empty> : <div className="divide-y divide-slate-800">{sources.map(source => <article key={source.id} className="space-y-2 py-4"><div className="flex flex-wrap gap-2"><Badge>{researchLabel(source.sourceType)}</Badge><Badge>{source.confidence} confidence</Badge></div><a href={sourceLink(source)} target="_blank" rel="noreferrer" className="block text-sm font-medium text-sky-300 hover:underline">{source.title} <ExternalLink size={12} className="inline" /></a><p className="text-xs text-slate-500">{source.authors || 'Author unreported'} · {source.year ?? 'Year unreported'} · {normalizeDoi(source.doi) || 'Direct source link'}</p><p className="text-xs text-slate-400">{source.notes || 'Source assessment not yet recorded.'}</p><div className="flex gap-2"><button className={primaryClass} onClick={() => { state.setActiveSource(source.id); state.setActiveTab('extract'); }}>Extract data</button><button className={buttonClass} onClick={() => replace({ ...sourceDefaults, title: source.title, authors: source.authors, doi: source.doi, url: source.url, sourceType: source.sourceType, confidence: source.confidence, notes: source.notes, year: source.year?.toString() ?? '', editId: source.id })}>Edit source</button></div></article>)}</div>}</section></div>
  </div>;
}
