import React, { useState } from 'react';
import { useResearchStore } from '../../store/useResearchStore';
import { useMaterialSpecimenStore } from '../../store/useMaterialSpecimenStore';
import { EVIDENCE_TYPES, TARGET_MODULES, type ResearchConfidence, type ResearchEvidenceType, type ResearchFinding, type ResearchTargetModule } from '../../types/research';
import { Empty, Field, Notice, Select, buttonClass, confidences, panelClass, primaryClass, useDraft } from './ResearchControls';

export function findingDraft(finding: ResearchFinding): Record<string, string> {
  return { editId: finding.id, sourceId: finding.sourceId, materialId: finding.materialId, materialName: finding.materialName, property: finding.property, value: String(finding.value), unit: finding.unit, rangeLow: finding.rangeLow?.toString() ?? '', rangeHigh: finding.rangeHigh?.toString() ?? '', uncertainty: finding.uncertainty?.toString() ?? '', uncertaintyDescription: finding.uncertaintyDescription, ...finding.conditions, locator: finding.locator, evidenceType: finding.evidenceType, confidence: finding.confidence, limitations: finding.limitations, validationReference: finding.validationReference, targetModule: finding.targetModule };
}
export function ResearchExtractionPanel() {
  const state = useResearchStore(), material = useMaterialSpecimenStore(s => s.activeSpecimen);
  const defaults = { editId: '', sourceId: state.activeSourceId, materialId: material.id, materialName: material.name, property: '', value: '', unit: '', rangeLow: '', rangeHigh: '', uncertainty: '', uncertaintyDescription: '', composition: '', process: '', machine: '', processParameters: '', powderCondition: '', heatTreatment: '', measurementMethod: '', locator: '', evidenceType: 'unresolved', confidence: 'unresolved', limitations: '', validationReference: '', targetModule: 'materials-db' };
  const { draft, patch, replace } = useDraft(`extraction:${state.activeBriefId}:${state.activeSourceId}`, defaults);
  const [errors, setErrors] = useState<string[]>([]), sources = state.sources.filter(s => s.briefId === state.activeBriefId);
  if (!sources.length) return <Empty>Save a source in the active brief before extracting numerical data.</Empty>;
  const optionalNumber = (key: string) => draft[key].trim() ? Number(draft[key]) : undefined;
  return <section className={panelClass}><h2 className="text-lg font-semibold text-slate-100">{draft.editId ? 'Revise extraction' : 'Extract a reported value'}</h2><p className="my-3 text-sm text-slate-400">Transcribe the original value and unit. Record missing conditions explicitly; do not infer measurements from a review or model output.</p><form className="space-y-5" onSubmit={event => { event.preventDefault(); const input = { briefId: state.activeBriefId, sourceId: draft.sourceId, materialId: draft.materialId, materialName: draft.materialName, property: draft.property, value: draft.value.trim() ? Number(draft.value) : NaN, unit: draft.unit, rangeLow: optionalNumber('rangeLow'), rangeHigh: optionalNumber('rangeHigh'), uncertainty: optionalNumber('uncertainty'), uncertaintyDescription: draft.uncertaintyDescription, conditions: { composition: draft.composition, process: draft.process, machine: draft.machine, processParameters: draft.processParameters, powderCondition: draft.powderCondition, heatTreatment: draft.heatTreatment, measurementMethod: draft.measurementMethod }, locator: draft.locator, evidenceType: draft.evidenceType as ResearchEvidenceType, confidence: draft.confidence as ResearchConfidence, limitations: draft.limitations, validationReference: draft.validationReference, targetModule: draft.targetModule as ResearchTargetModule, reviewNote: '' }; const result = draft.editId ? state.reviseFinding(draft.editId, input) : state.addFinding(input); setErrors(result.errors); if (!result.errors.length) { replace({ ...defaults, sourceId: draft.sourceId }); state.setActiveTab('registry'); } }}>
    <Select label="Original source" value={draft.sourceId} onChange={state.setActiveSource} options={[{ value: '', label: 'Select a source' }, ...sources.map(source => ({ value: source.id, label: source.title }))]} />
    <div className="rounded-lg border border-slate-700 bg-slate-950 p-3"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-slate-200">Associated material: <strong>{draft.materialName}</strong></p><button className={buttonClass} type="button" onClick={() => replace({ ...draft, materialId: material.id, materialName: material.name })}>Use active material</button></div><p className="mt-1 break-all text-[11px] text-slate-500">{draft.materialId}. Material association is preserved when you switch workspaces. Composition below must describe the source specimen.</p></div>
    <div className="grid gap-4 sm:grid-cols-3"><Field label="Property / quantity" value={draft.property} onChange={value => patch('property', value)} required placeholder="Melt pool width" /><Field label="Reported value" type="number" value={draft.value} onChange={value => patch('value', value)} required /><Field label="Original unit" value={draft.unit} onChange={value => patch('unit', value)} required placeholder="µm, MPa, W/(m·K), or 1" /><Field label="Range lower (same unit)" type="number" value={draft.rangeLow} onChange={value => patch('rangeLow', value)} /><Field label="Range upper (same unit)" type="number" value={draft.rangeHigh} onChange={value => patch('rangeHigh', value)} /><Field label="Absolute ± uncertainty (same unit)" type="number" value={draft.uncertainty} onChange={value => patch('uncertainty', value)} /></div>
    <Field label="Uncertainty definition / sample count / confidence interval" value={draft.uncertaintyDescription} onChange={value => patch('uncertaintyDescription', value)} placeholder="Record the reported definition, or explicitly state not reported." />
    <div className="grid gap-4 sm:grid-cols-2">{(['composition', 'process', 'machine', 'processParameters', 'powderCondition', 'heatTreatment', 'measurementMethod', 'locator'] as const).map(key => <Field key={key} label={{ composition: 'Source composition and basis (wt.% / at.%)', process: 'Process / manufacturing route', machine: 'Machine / beam specification', processParameters: 'Process parameters with units', powderCondition: 'Powder condition / lot / PSD', heatTreatment: 'Heat treatment / specimen condition', measurementMethod: 'Measurement or simulation method', locator: 'Page / table / figure / section reference' }[key]} value={draft[key]} onChange={value => patch(key, value)} />)}</div>
    <div className="grid gap-4 sm:grid-cols-3"><Select label="Evidence type" value={draft.evidenceType} options={EVIDENCE_TYPES} onChange={value => patch('evidenceType', value)} /><Select label="Finding confidence (user assessed)" value={draft.confidence} options={confidences} onChange={value => patch('confidence', value)} /><Select label="Intended target module" value={draft.targetModule} options={TARGET_MODULES} onChange={value => patch('targetModule', value)} /></div>
    {['validated-simulation', 'calibrated-simulation'].includes(draft.evidenceType) && <Field label="Experimental validation / calibration reference and applicable conditions" value={draft.validationReference} onChange={value => patch('validationReference', value)} multiline placeholder="Identify the independent experiment or calibration dataset. Numerical convergence and energy conservation do not establish experimental validation." />}
    <Field label="Limitations / applicability / missing information" value={draft.limitations} onChange={value => patch('limitations', value)} multiline /><Notice messages={errors} /><div className="flex gap-2"><button className={primaryClass} type="submit">{draft.editId ? 'Save revised draft' : 'Save extraction for review'}</button>{draft.editId && <button className={buttonClass} type="button" onClick={() => { replace({ ...defaults, editId: '' }); state.setActiveTab('registry'); }}>Cancel revision</button>}</div>
  </form></section>;
}
