import React, { useState } from 'react';
import { ExternalLink } from 'lucide-react';
import { useResearchStore } from '../../store/useResearchStore';
import { EVIDENCE_TYPES, TARGET_MODULES, type ResearchFinding, type ResearchTargetModule } from '../../types/research';
import { compareResearchFindings, researchEvidenceLabel, researchIntegrationIssues, researchLabel, researchReviewIssues, sourceLink } from '../../utils/researchRegistry';
import { findingDraft } from './ResearchExtractionPanel';
import { Badge, Empty, Field, Notice, Select, buttonClass, panelClass, primaryClass, useDraft } from './ResearchControls';

export function ResearchRegistryPanel() {
  const state = useResearchStore();
  const { draft, patch } = useDraft('registry', { filter: '', evidence: '', compareA: '', compareB: '' });
  const findings = state.findings.filter(f => (!draft.filter || `${f.materialName} ${f.property} ${state.sources.find(s => s.id === f.sourceId)?.title}`.toLowerCase().includes(draft.filter.toLowerCase())) && (!draft.evidence || f.evidenceType === draft.evidence));
  const a = state.findings.find(f => f.id === draft.compareA), b = state.findings.find(f => f.id === draft.compareB);
  const [messages, setMessages] = useState<string[]>([]);
  return <div className="space-y-5"><section className={panelClass}><h2 className="text-lg font-semibold text-slate-100">MetalliX evidence registry</h2><p className="my-2 text-sm text-slate-400">All briefs share this registry. Reviewed links are visible in target modules and qualification reports. Linking a finding does not replace solver parameters or create experimental validation.</p><div className="grid gap-4 sm:grid-cols-2"><Field label="Filter material, property, or source" value={draft.filter} onChange={value => patch('filter', value)} /><Select label="Evidence type filter" value={draft.evidence} onChange={value => patch('evidence', value)} options={[{ value: '', label: 'All evidence types' }, ...EVIDENCE_TYPES.map(value => ({ value, label: researchLabel(value) }))]} /></div></section>
    {state.findings.length > 1 && <section className={panelClass}><h3 className="mb-3 font-semibold text-slate-200">Source comparison</h3><div className="grid gap-4 sm:grid-cols-2">{(['compareA', 'compareB'] as const).map((key, index) => <Select key={key} label={`Finding ${index + 1}`} value={draft[key]} onChange={value => patch(key, value)} options={[{ value: '', label: 'Select a finding' }, ...state.findings.map(f => ({ value: f.id, label: `${f.materialName} · ${f.property} ${f.value} ${f.unit} · ${state.sources.find(s => s.id === f.sourceId)?.title}` }))]} />)}</div>{a && b && a.id !== b.id && <div className="mt-4 space-y-3"><p className="text-sm text-amber-200">{compareResearchFindings(a, b)}</p><div className="grid gap-4 sm:grid-cols-2">{[a, b].map(f => <div key={f.id} className="rounded-lg border border-slate-700 p-3 text-xs text-slate-400"><p className="mb-2 text-slate-200">{f.value} {f.unit} · {researchEvidenceLabel(f)} · {f.confidence} confidence</p><p>Process: {f.conditions.process || 'Unreported'} · Method: {f.conditions.measurementMethod || 'Unreported'}</p><p>Parameters: {f.conditions.processParameters || 'Unreported'}</p><p>Heat treatment: {f.conditions.heatTreatment || 'Unreported'} · Powder: {f.conditions.powderCondition || 'Unreported'}</p><p>Uncertainty: {f.uncertaintyDescription || 'Unreported'}</p><p>Limitations: {f.limitations || 'Unreported'}</p></div>)}</div><button className={buttonClass} onClick={() => { const flagged = !a.conflictsWith.includes(b.id), result = state.setConflict(a.id, b.id, flagged); setMessages(result.errors.length ? result.errors : [flagged ? 'Conflict flagged. Module links for both findings were withdrawn.' : 'Conflict flag cleared. Review and explicitly relink findings when appropriate.']); }}>{a.conflictsWith.includes(b.id) ? 'Clear conflict after review' : 'Flag conflicting evidence'}</button></div>}<div className="mt-3"><Notice messages={messages} /></div></section>}
    {!findings.length ? <Empty>No extractions match. Save a numerical extraction from an original source to populate the registry.</Empty> : findings.map(finding => <FindingCard key={finding.id} finding={finding} />)}
  </div>;
}

function FindingCard({ finding }: { key?: string; finding: ResearchFinding }) {
  const state = useResearchStore(), source = state.sources.find(s => s.id === finding.sourceId);
  const { draft, patch } = useDraft(`review:${finding.id}`, { reviewNote: finding.reviewNote, feedback: '', reference: '', outcome: 'inconclusive', target: finding.targetModule });
  const [messages, setMessages] = useState<string[]>([]);
  const reviewIssues = researchReviewIssues({ ...finding, reviewNote: draft.reviewNote }, source);
  const integrationIssues = researchIntegrationIssues(finding, source, draft.target as ResearchTargetModule);
  const links = state.integrations.filter(i => i.findingId === finding.id), feedback = state.feedback.filter(item => item.findingId === finding.id);
  return <article className={panelClass} data-testid="research-finding"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="mb-2 flex flex-wrap gap-2"><Badge>{researchEvidenceLabel(finding)}</Badge><Badge>{finding.reviewStatus === 'reviewed' ? 'Reviewed extraction (user assessed)' : 'Draft · review required'}</Badge><Badge>{finding.confidence} confidence</Badge>{finding.conflictsWith.length > 0 && <span className="text-xs text-amber-300">Conflicting evidence flagged</span>}</div><h3 className="text-lg font-semibold text-slate-100">{finding.property}: <span className="text-sky-300">{finding.value} {finding.unit}</span></h3><p className="mt-1 text-xs text-slate-400">{finding.materialName} · {finding.locator || 'Source locator missing'}</p></div><button className={buttonClass} onClick={() => { state.setActiveBrief(finding.briefId); state.setActiveSource(finding.sourceId); state.setDraft(`extraction:${finding.briefId}:${finding.sourceId}`, findingDraft(finding)); state.setActiveTab('extract'); }}>Revise extraction</button></div>
    {source && <a className="mt-3 block text-xs text-sky-400 hover:underline" href={sourceLink(source)} target="_blank" rel="noreferrer">{source.title} · {source.doi || 'Direct source'} <ExternalLink size={11} className="inline" /></a>}
    <div className="mt-4 grid gap-x-6 gap-y-2 text-xs sm:grid-cols-2"><p className="text-slate-400">Range: <span className="text-slate-200">{finding.rangeLow !== undefined ? `${finding.rangeLow} – ${finding.rangeHigh} ${finding.unit}` : 'Not reported'}</span></p><p className="text-slate-400">Uncertainty: <span className="text-slate-200">{finding.uncertainty !== undefined ? `±${finding.uncertainty} ${finding.unit}. ` : ''}{finding.uncertaintyDescription || 'Not reported'}</span></p>{Object.entries(finding.conditions).map(([key, value]) => <p key={key} className="text-slate-400">{key.replace(/([A-Z])/g, ' $1')}: <span className="text-slate-200">{value || 'Not reported'}</span></p>)}</div><p className="mt-3 text-xs text-amber-200">Limitations: {finding.limitations || 'Not recorded; review is blocked.'}</p>{finding.validationReference && <p className="mt-2 text-xs text-slate-400">Reported validation / calibration basis: {finding.validationReference}</p>}
    <div className="mt-5 grid gap-5 border-t border-slate-800 pt-4 lg:grid-cols-2"><div className="space-y-3"><Field label="Review rationale and applicability" value={draft.reviewNote} onChange={value => patch('reviewNote', value)} multiline /><button className={primaryClass} disabled={reviewIssues.length > 0} onClick={() => { const result = state.reviewFinding(finding.id, draft.reviewNote); setMessages(result.errors.length ? result.errors : ['Extraction reviewed. Its evidence type and scientific scope are unchanged.']); }}>Record extraction review</button>{reviewIssues.length > 0 && <p className="text-xs text-amber-300">Review requirements: {reviewIssues.join(' ')}</p>}<Select label="Link reviewed evidence to" value={draft.target} options={TARGET_MODULES} onChange={value => patch('target', value)} /><button className={buttonClass} disabled={integrationIssues.length > 0} onClick={() => { const result = state.integrateFinding(finding.id, draft.target as ResearchTargetModule); setMessages(result.errors.length ? result.errors : ['Evidence linked to the target module. Solver inputs remain controlled by the engineering workflow.']); }}>Link evidence to module</button>{integrationIssues.length > 0 && <p className="text-xs text-slate-500">Integration requirements: {integrationIssues.join(' ')}</p>}{links.length > 0 && <p className="text-xs text-sky-300">Linked: {links.map(link => researchLabel(link.targetModule)).join(', ')}</p>}</div>
      <div className="space-y-3"><h4 className="text-sm font-semibold text-slate-200">Simulation / experiment feedback</h4><Select label="Outcome" value={draft.outcome} onChange={value => patch('outcome', value)} options={['inconclusive', 'supports', 'contradicts']} /><Field label="Experiment ID / job ID / direct report reference" value={draft.reference} onChange={value => patch('reference', value)} /><Field label="Observation, comparison conditions, and limitations" value={draft.feedback} onChange={value => patch('feedback', value)} multiline /><button className={buttonClass} onClick={() => { const result = state.addFeedback({ findingId: finding.id, outcome: draft.outcome as 'supports' | 'contradicts' | 'inconclusive', experimentOrJobReference: draft.reference, note: draft.feedback }); setMessages(result.errors.length ? result.errors : [draft.outcome === 'contradicts' ? 'Contradictory feedback recorded. Review and module links were withdrawn.' : 'Evidence feedback recorded. No automatic validation promotion was made.']); }}>Record feedback</button>{feedback.length > 0 && <ul className="space-y-2 text-xs text-slate-400">{feedback.map(item => <li key={item.id} className="rounded border border-slate-700 p-2"><strong className="text-slate-200">{researchLabel(item.outcome)}</strong> · {item.experimentOrJobReference}<p className="mt-1">{item.note}</p><p className="mt-1 text-slate-500">{new Date(item.createdAt).toLocaleString()}</p></li>)}</ul>}</div></div><div className="mt-3"><Notice messages={messages} /></div>
  </article>;
}
